### ISSUE TITLE
Missing x86_64 architecture for visionOS simulator

### ISSUE THREAD

**Issue by BProg** [mihai8804858/swift-libass#1]
When building the app for testing on any visionOS simulator device, it fails with following message
<img width="980" alt="Screenshot 2024-06-27 at 14 46 27" src="https://github.com/mihai8804858/swift-libass/assets/11962191/14e01d1f-1890-4245-876d-5012f8c6c1c4">

I am trying to make the updates myself, but am not able to run the `./build-libraries.sh` and the scripts inside `ffmpeg-kit` are failing

**Comment by mihai8804858** [comment]
Afaik visionOS doesn't support x86_64 and requires Apple Silicon.

![image](https://github.com/mihai8804858/swift-libass/assets/7620639/7f0c1b9f-70ac-4756-83d3-77f4ca789eab)

**Comment by BProg** [comment]
Yeah, but simulator itself is a macos app, like other simulators
<img width="330" alt="Screenshot 2024-07-01 at 08 47 46" src="https://github.com/mihai8804858/swift-libass/assets/11962191/5f8d2d3b-6e26-4d21-b9f6-3244c1bbb55b">

You can try to build for testing following empty project using the `any visionOS simulator device` as device `⇧ ⌘ U`
[EmptyVisionLibASS.zip](https://github.com/user-attachments/files/16048407/EmptyVisionLibASS.zip)

**Comment by BProg** [comment]
Found it's a missing architecture from the function-xros.sh script from the ffmpeg-kit repo

**Comment by mihai8804858** [comment]
Fixed in [1.2.0](https://github.com/mihai8804858/swift-libass/releases/tag/1.2.0).
